package eu.kanade.tachiyomi.extension.en.sacredtextslibrary

import eu.kanade.tachiyomi.network.GET
import eu.kanade.tachiyomi.source.model.FilterList
import eu.kanade.tachiyomi.source.model.MangasPage
import eu.kanade.tachiyomi.source.model.Page
import eu.kanade.tachiyomi.source.model.SChapter
import eu.kanade.tachiyomi.source.model.SManga
import eu.kanade.tachiyomi.source.online.HttpSource
import okhttp3.Headers
import okhttp3.Request
import okhttp3.Response
import org.json.JSONArray
import org.json.JSONObject

/**
 * Sacred Texts Library — a Tachiyomi / Mihon / Aniyomi source for
 * https://yeshe-tsogyel-library.netlify.app
 *
 * The library's texts are long-form writing, but reader apps only understand
 * image pages. A manifest JSON published alongside the site (see MANIFEST_URL
 * and README.md) lists every text, its sections, and the pre-rendered page
 * images for each section. This source reads everything from that manifest;
 * it never scrapes the site HTML.
 *
 * Mapping:
 *   text    -> manga entry   (SManga.url = text id)
 *   section -> chapter       (SChapter.url = "textId/sectionId")
 *   page    -> image URL     (Page.imageUrl, served from the site)
 */
open class SacredTextsLibrary : HttpSource() {

    override val name = "Sacred Texts Library"

    override val baseUrl = "https://yeshe-tsogyel-library.netlify.app"

    override val lang = "en"

    override val supportsLatest = true

    /**
     * Bump on every source change. The app computes the stable source id
     * from name + lang + versionId, so index.json's source id must be
     * regenerated if this ever changes (see README.md).
     */
    override val versionId = 1

    companion object {
        /**
         * Manifest generated by the page-image rendering step (phase 3).
         * See README.md for the exact JSON contract.
         */
        const val MANIFEST_URL = "https://yeshe-tsogyel-library.netlify.app/extension/manifest.json"
    }

    // ------------------------------------------------------------------
    // Request builders — every list/detail call goes through the manifest.
    // ------------------------------------------------------------------

    override fun popularMangaRequest(page: Int): Request = GET(MANIFEST_URL, headers)

    override fun latestUpdatesRequest(page: Int): Request = GET(MANIFEST_URL, headers)

    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
        lastSearchQuery = query
        return GET(MANIFEST_URL, headers)
    }

    override fun mangaDetailsRequest(manga: SManga): Request = GET(MANIFEST_URL, headers)

    override fun chapterListRequest(manga: SManga): Request {
        // chapterListParse only receives the Response, so the text id travels here.
        currentTextId = manga.url
        return GET(MANIFEST_URL, headers)
    }

    override fun pageListRequest(chapter: SChapter): Request {
        // pageListParse only receives the Response, so the chapter key travels here.
        currentChapterKey = chapter.url
        return GET(MANIFEST_URL, headers)
    }

    private var lastSearchQuery: String = ""
    private var currentTextId: String = ""
    private var currentChapterKey: String = ""

    // ------------------------------------------------------------------
    // Parsers
    // ------------------------------------------------------------------

    override fun popularMangaParse(response: Response): MangasPage {
        val entries = manifestTexts(response).map { it.toSManga() }
        return MangasPage(entries, hasNextPage = false)
    }

    override fun latestUpdatesParse(response: Response): MangasPage = popularMangaParse(response)

    override fun searchMangaParse(response: Response): MangasPage {
        val q = lastSearchQuery.trim().lowercase()
        val entries = manifestTexts(response)
            .filter { q.isEmpty() || it.title.lowercase().contains(q) || it.author.lowercase().contains(q) }
            .map { it.toSManga() }
        return MangasPage(entries, hasNextPage = false)
    }

    override fun mangaDetailsParse(response: Response): SManga {
        return manifestTexts(response).first { it.id == currentTextId }.toSManga()
    }

    override fun chapterListParse(response: Response): List<SChapter> {
        val text = manifestTexts(response).first { it.id == currentTextId }
        return text.sections.mapIndexed { index, section ->
            SChapter.create().apply {
                url = "${text.id}/${section.id}"
                name = section.title
                chapter_number = index + 1f
                date_upload = 0L
            }
        }.reversed() // newest section first, like a chapter list
    }

    override fun pageListParse(response: Response): List<Page> {
        val (textId, sectionId) = currentChapterKey.split("/", limit = 2)
        val section = manifestTexts(response)
            .first { it.id == textId }
            .sections.first { it.id == sectionId }
        return section.pages.mapIndexed { index, imageUrl ->
            Page(index, imageUrl = imageUrl)
        }
    }

    // Page image URLs are direct, so the default imageRequest (GET on the
    // image URL with our headers) is all we need — no override required.

    // ------------------------------------------------------------------
    // Misc
    // ------------------------------------------------------------------

    override fun getMangaUrl(manga: SManga): String = "$baseUrl/#text/${manga.url}"

    override fun getChapterUrl(chapter: SChapter): String = "$baseUrl/#section/${chapter.url}"

    override fun getFilterList(): FilterList = FilterList()

    override fun headersBuilder(): Headers.Builder = Headers.Builder()
        .add("User-Agent", "Mozilla/5.0 (Linux; Android 10; Mobile) SacredTextsLibrary/1.0")

    // ------------------------------------------------------------------
    // Manifest model (org.json ships with Android — no extra dependency).
    // ------------------------------------------------------------------

    private fun manifestTexts(response: Response): List<LibraryText> {
        val root = JSONObject(response.body.string())
        val out = mutableListOf<LibraryText>()
        val texts: JSONArray = root.getJSONArray("texts")
        for (i in 0 until texts.length()) {
            val t = texts.getJSONObject(i)
            val sections = mutableListOf<LibrarySection>()
            val sarr = t.optJSONArray("sections") ?: JSONArray()
            for (j in 0 until sarr.length()) {
                val s = sarr.getJSONObject(j)
                val pages = mutableListOf<String>()
                val parr = s.optJSONArray("pages") ?: JSONArray()
                for (k in 0 until parr.length()) pages.add(parr.getString(k))
                sections.add(LibrarySection(s.getString("id"), s.getString("title"), pages))
            }
            out.add(
                LibraryText(
                    id = t.getString("id"),
                    title = t.getString("title"),
                    author = t.optString("author", ""),
                    description = t.optString("description", ""),
                    cover = t.optString("cover", ""),
                    sections = sections,
                ),
            )
        }
        return out
    }

    private data class LibraryText(
        val id: String,
        val title: String,
        val author: String,
        val description: String,
        val cover: String,
        val sections: List<LibrarySection>,
    ) {
        fun toSManga(): SManga = SManga.create().apply {
            url = id
            title = this@LibraryText.title
            author = this@LibraryText.author
            description = this@LibraryText.description
            if (cover.isNotBlank()) thumbnail_url = cover
            status = SManga.COMPLETED
            initialized = true
        }
    }

    private data class LibrarySection(
        val id: String,
        val title: String,
        val pages: List<String>,
    )
}
